Revert "scsi: sg: NO_DXFER move to/from kernel buffers"
This reverts commit b32ac463cb59e758b4560260fd168a2b4ea6e81a.

drivers/scsi/sg.c:2990:34: error: variable 'k' is uninitialized when
used here [-Werror,-Wuninitialized]
        bio = sg_mk_kern_bio(num_sgat - k);
                                        ^
drivers/scsi/sg.c:2977:7: note: initialize the variable 'k' to silence
this warning
        int k, ln;
             ^
              = 0
1 error generated.

Signed-off-by: Nathan Chancellor <nathan@kernel.org>